logging:
  level:
    fr:
      rewrite:
        back: INFO
spring:
  application:
    name: RewriteBack
  data:
    redis:
      database: 0
      url: redis://localhost:6379
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8080
